CREATE DATABASE IF NOT EXISTS wireguard;
USE wireguard;

CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ip_address VARCHAR(15) NOT NULL UNIQUE
);
